// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/edit.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/login.ts";
import * as $4 from "./routes/api/refresh.ts";
import * as $5 from "./routes/edit.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/logout.tsx";
import * as $$0 from "./islands/CopyLink.tsx";
import * as $$1 from "./islands/CustomShare.tsx";
import * as $$2 from "./islands/Header.tsx";
import * as $$3 from "./islands/Menu.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/edit.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/login.ts": $3,
    "./routes/api/refresh.ts": $4,
    "./routes/edit.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/logout.tsx": $7,
  },
  islands: {
    "./islands/CopyLink.tsx": $$0,
    "./islands/CustomShare.tsx": $$1,
    "./islands/Header.tsx": $$2,
    "./islands/Menu.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
